PrintManagement.AdminApp/PrintManagement.AdminApp/Controllers/Components/PagerViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using PrintManagement.ApiIntegration.Common;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PrintManagement.AdminApp.Controllers.Components {
    public class PagerViewComponent : ViewComponent {
        public Task<IViewComponentResult> InvokeAsync(PagedResultBase result) {
            return Task.FromResult((IViewComponentResult)View("Default", result));
        }
    }
}

PrintManagement.AdminApp/PrintManagement.AdminApp/Controllers/DepartmentController.cs
using System;
using System.Collections.Generic;
using System.IdentityModel.Tokens.Jwt;
using System.Linq;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;
using Microsoft.IdentityModel.Logging;
using Microsoft.IdentityModel.Tokens;
using PrintManagement.ApiIntegration;
using PrintManagement.ApiIntegration.Common;

namespace PrintManagement.AdminApp.Controllers {
    public class DepartmentController : BaseController {
        private readonly BaseApiClient _baseApiClient;
        private readonly IDepartmentApiClient _departmentApiClient;
        private readonly ILogger _logger;

        public DepartmentController(IDepartmentApiClient departmentApiClient,
            ILogger logger, BaseApiClient baseApiClient) {
            _logger = logger;
            _departmentApiClient = departmentApiClient;
            _baseApiClient = baseApiClient;
        }

        public async Task<IActionResult> Index(string keyword = "empty", int pageIndex = 1, int pageSize = 10) {
            if (string.IsNullOrEmpty(keyword))
                keyword = "empty";

            var data = await _departmentApiClient.GetAllDepartment(keyword, pageSize, pageIndex);

            if (!keyword.Equals("empty"))
                ViewBag.Keyword = keyword;

            if (TempData["result"] != null)
                ViewBag.SuccessMsg = TempData["result"];

            ViewData["Token"] = HttpContext.Session.GetString(SystemConstants.AppSetting.Token);

            return View(data.ResultObj);
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Details(Guid id) {
            var result = await _departmentApiClient.GetDepartmentById(id);
            return View(result.ResultObj);
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create() {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create(DepartmentDTO department) {
            if (!ModelState.IsValid)
                return View();

            department.CreatedBy = User.Claims.FirstOrDefault()?.Value;
            department.CreatedDate = DateTime.Now;
            department.ModifiedBy = User.Claims.FirstOrDefault()?.Value;
            department.ModifiedDate = DateTime.Now;

            var result = await _departmentApiClient.CreateDepartment(department);
            if (result.IsSuccessed) {
                TempData["result"] = "Thêm mới phòng ban thành công";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", result.Message);
            return View(department);
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(Guid id) {
            var result = await _departmentApiClient.GetDepartmentById(id);
            if (result.IsSuccessed) {
                return View(result.ResultObj);
            }
            return RedirectToAction("Error", "Home");
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(DepartmentDTO request) {
            if (!ModelState.IsValid)
                return View();

            request.ModifiedBy = User.Claims.FirstOrDefault()?.Value;
            request.ModifiedDate = DateTime.Now;

            var result = await _departmentApiClient.UpdateDepartment(request.Oid, request);
            if (result.IsSuccessed) {
                TempData["result"] = "Cập nhật phòng ban thành công";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", result.Message);
            return View(request);
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(Guid id) {
            if (!ModelState.IsValid)
                return View();

            var result = await _departmentApiClient.DeleteDepartment(id);
            if (result.IsSuccessed) {
                TempData["result"] = "Xóa phòng ban thành công";
            }
            ModelState.AddModelError("", result.Message);
            return RedirectToAction("Index");
        }
    }
}

PrintManagement.AdminApp/PrintManagement.AdminApp/Views/Department/Create.cshtml
@model RegisterRequest

@{
    ViewData["Title"] = "Phòng ban";
}

@section header
{
    Phòng ban - Thêm mới phòng ban
}

<div class="container-fluid">
    <div class="card mb-4">
        <div class="card-body">
            <div class="col-md-4">
                <form asp-action="Create">
                    <div asp-validation-summary="All" class="text-danger"></div>
                    <div class="form-group">
                        <label class="control-label">Tên phòng ban</label>
                        <input asp-for="Name" class="form-control" required />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    @*<div class="form-group">
                        <label class="control-label">Ghi chú</label>
                        <input asp-for="Note" class="form-control" />
                        <span asp-validation-for="Note" class="text-danger"></span>
                        </div>*@
                    @*<div class="form-group">
                        <input type="submit" value="Lưu lại" class="btn btn-primary" />
                    </div>*@


                    <button type="submit" class="btn btn-primary" style="width:110px">
                        <a class="fa fa-save"></a> &nbsp;Lưu lại
                    </button>
                    <button type="button" class="btn btn-warning" style="width:110px">
                        <a class="fa fa-th-list"></a> &nbsp;
                        @Html.ActionLink("Danh sách", "Index")
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>

PrintManagement.AdminApp/PrintManagement.AdminApp/Views/Department/Details.cshtml
@model PrintManagement.ApiIntegration.DepartmentDTO

@{
    ViewData["Title"] = "Phòng ban";
}

@section header
{
    Phòng ban - Chi tiết phòng ban (#@Model.Name)
}

<div class="container-fluid">
    <div class="card mb-4">
        <div class="card-body">
            <div class="col-md-12">
                <dl class="row">
                    <dt class="col-sm-2">
                        Tên phòng ban:
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Name)
                    </dd>
                    @*<dt class="col-sm-2">
                        Ghi chú:
                        </dt>
                        <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Note)
                        </dd>*@
                    <dt class="col-sm-2">
                        Người tạo:
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.CreatedBy)
                    </dd>
                    <dt class="col-sm-2">
                        Ngày tạo:
                    </dt>
                    <dd class="col-sm-10">
                        @Html.Raw(Convert.ToDateTime(Model.CreatedDate).ToString("dd/MM/yyyy"))
                    </dd>
                    <dt class="col-sm-2">
                        Người cập nhật:
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.ModifiedBy)
                    </dd>
                    <dt class="col-sm-2">
                        Ngày cập nhật:
                    </dt>
                    <dd class="col-sm-10">
                        @Html.Raw(Convert.ToDateTime(Model.ModifiedDate).ToString("dd/MM/yyyy"))
                    </dd>
                </dl>
                <button type="button" class="btn btn-primary">
                    <a class="fa fa-edit"></a> &nbsp;
                    @Html.ActionLink("Chỉnh sửa", "Edit", new { id = Model.Oid})
                </button>
                <button type="button" class="btn btn-warning">
                    <a class="fa fa-th-list"></a> &nbsp;
                    @Html.ActionLink("Danh sách", "Index")
                </button>
            </div>
        </div>
    </div>
</div>

PrintManagement.AdminApp/PrintManagement.AdminApp/Views/Department/Edit.cshtml
@model DepartmentDTO
@{
    ViewData["Title"] = "Phòng ban";
}

@section header
{
    Phòng ban - Cập nhật phòng ban (#@Model.Name)
}

<div class="container-fluid">
    <div class="card mb-4">
        <div class="card-body">
            <div class="col-md-4">
                <form asp-action="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <input type="hidden" asp-for="Oid" class="form-control" />

                    <div class="form-group">
                        <label class="control-label">Tên phòng ban</label>
                        <input asp-for="Name" class="form-control" required />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    @*<div class="form-group">
                        <label class="control-label">Ghi chú</label>
                        <input asp-for="Note" class="form-control" />
                        <span asp-validation-for="Note" class="text-danger"></span>
                        </div>*@

                    <button type="submit" class="btn btn-primary" style="width:110px">
                        <a class="fa fa-save"></a> &nbsp;Lưu lại
                    </button>
                    <button type="button" class="btn btn-warning" style="width:110px">
                        <a class="fa fa-th-list"></a> &nbsp;
                        @Html.ActionLink("Danh sách", "Index")
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>

PrintManagement.AdminApp/PrintManagement.AdminApp/Views/Department/Index.cshtml
@model PagedResult<DepartmentDTO>

@{
    ViewData["Title"] = "Phòng ban";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";

    var token = ViewData["Token"] as string;

    var i = Model.PageSize * (Model.PageIndex - 1);
    string GetNumerOrder()
    {
        i++;
        return Convert.ToString(i);
    }
}
@section header
{
    Phòng ban - Danh sách phòng ban
}

@section Scripts{
<script>
    setTimeout(function () {
        $('#msgAlert').fadeOut('slow');
    }, 2000);
</script>
}
<div class="container-fluid">
    <div class="card mb-12">
        <div class="card-header" style="margin-bottom:12px">
            <div class="row">
                <div class="col-md-6 col-xs-12">
                    <form asp-action="Index" method="get">
                        <div class="row">
                            <div class="col-md-9">
                                <input type="text" value="@ViewBag.Keyword" name="keyword" class="form-control" placeholder="Nhập nội dung tìm kiếm..." />
                            </div>
                            <div class="cold-md-3">
                                <button type="submit" class="btn btn-primary">Tìm kiếm</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="col-md-6 col-xs-12">
                    <button type="button" class="btn btn-success btn-admin" style="margin-bottom:10px; margin-left:5px; float: right; width:110px">
                        <i class="fa fa-plus-square"></i> &nbsp;
                        @Html.ActionLink("Thêm mới", "Create", "Department")
                    </button>
                </div>
            </div>
        </div>

        <div class="card-body">
            <div class="row">
                @if (ViewBag.SuccessMsg != null)
                {
                    <div id="msgAlert" class="alert alert-success" role="alert" style="position:fixed;z-index:99999;top:14%;right:35%">
                        @ViewBag.SuccessMsg
                    </div>
                }
            </div>
            <div class="table-responsive">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>
                                STT
                            </th>
                            <th>
                                Tên phòng ban
                            </th>
                            <th>
                                Ngày tạo
                            </th>
                            <th>
                                Chức năng
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.Items)
                        {
                            <tr>
                                <td>
                                    @Html.Raw(GetNumerOrder())
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Name)
                                </td>
                                <td>
                                    @Html.Raw(@Convert.ToDateTime(item.CreatedDate).ToString("dd/MM/yyyy"))
                                </td>
                                <td>
                                    @Html.ActionLink("Xem", "Details", new { id = item.Oid }) |
                                    @Html.ActionLink("Sửa", "Edit", new { id = item.Oid }) |
                                    @Html.ActionLink("Xóa", "Delete", new { id = item.Oid },new { onclick = "return confirm('Chắc chắn muốn xoá?');" })
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            @await Component.InvokeAsync("Pager", Model)
        </div>
    </div>
</div>