PrintManagement.AdminApp/PrintManagement.AdminApp/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.IdentityModel.Tokens.Jwt;
using System.Linq;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Options;
using Microsoft.IdentityModel.Logging;
using Microsoft.IdentityModel.Tokens;
using PrintManagement.ApiIntegration;
using PrintManagement.ApiIntegration.Common;

namespace PrintManagement.AdminApp.Controllers {
    public class LoginController : Controller {
        private readonly IUserApiClient _userApiClient;
        private readonly AppSettings _appSettings;
        public LoginController(IUserApiClient userApiClient, IOptionsMonitor<AppSettings> optionsMonitor) {
            _userApiClient = userApiClient;
            _appSettings = optionsMonitor.CurrentValue;
        }

        [HttpGet]
        public async Task<IActionResult> Index() {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(LoginRequest request) {
            if (!ModelState.IsValid)
                return View(ModelState);

            var result = await _userApiClient.AuthenticateAsync(request);
            if (result.ResultObj == null) {
                ModelState.AddModelError("", result.Message);
                return View();
            }
            var userPrincipal = this.ValidateToken(result.ResultObj);

            var authProperties = new AuthenticationProperties {
                ExpiresUtc = DateTimeOffset.UtcNow.AddMinutes(30),
                IsPersistent = false
            };

            // Set token into session
            HttpContext.Session.SetString(SystemConstants.AppSetting.Token, result.ResultObj);

            await HttpContext.SignInAsync(
                        CookieAuthenticationDefaults.AuthenticationScheme,
                        userPrincipal,
                        authProperties);

            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public async Task<IActionResult> ForgetPassword() {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> ForgetPassword(ForgetPasswordRequest request) {
            if (!ModelState.IsValid)
                return View(ModelState);

            var allUser = (await _userApiClient.GetAllUserAsync()).ResultObj;
            var user = allUser.FirstOrDefault(x => x.UserName == request.UserName && x.Email == request.Email);
            if (user != null) {

            }
            else {
                ModelState.AddModelError("", "Tài khoản không tồn tại");
                return View();
            }
            //var result = await _userApiClient.AuthenticateAsync(request);
            //if (result.ResultObj == null) {
            //    ModelState.AddModelError("", result.Message);
            //    return View();
            //}
            //var userPrincipal = this.ValidateToken(result.ResultObj);

            //var authProperties = new AuthenticationProperties {
            //    ExpiresUtc = DateTimeOffset.UtcNow.AddMinutes(30),
            //    IsPersistent = false
            //};

            //// Set token into session
            //HttpContext.Session.SetString(SystemConstants.AppSetting.Token, result.ResultObj);

            //await HttpContext.SignInAsync(
            //            CookieAuthenticationDefaults.AuthenticationScheme,
            //            userPrincipal,
            //            authProperties);

            return RedirectToAction("Index", "Home");
        }

        private ClaimsPrincipal ValidateToken(string jwtToken) {
            IdentityModelEventSource.ShowPII = true;

            SecurityToken validatedToken;
            TokenValidationParameters validationParameters = new TokenValidationParameters();

            validationParameters.ValidateLifetime = true;
            validationParameters.ValidateIssuer = false;
            validationParameters.ValidateAudience = false;
            validationParameters.IssuerSigningKey =
                new SymmetricSecurityKey(Encoding.UTF8.GetBytes(_appSettings.Secretkey));

            ClaimsPrincipal principal = new JwtSecurityTokenHandler().ValidateToken(jwtToken, validationParameters, out validatedToken);

            return principal;
        }
    }
}

PrintManagement.AdminApp/PrintManagement.AdminApp/Views/Login/ForgetPassword.cshtml
@model ForgetPasswordRequest
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>GreenPrint HT | Quên mật khẩu</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.4 -->

    <link href="~/template/Admin/LTE/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <!-- Font Awesome Icons -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <!-- Theme style -->
    <link href="~/template/Admin/LTE/dist/css/AdminLTE.min.css" rel="stylesheet" type="text/css" />
    <!-- iCheck -->
    <link href="~/template/Admin/LTE/plugins/iCheck/square/blue.css" rel="stylesheet" type="text/css" />

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body class="login-page" style="background-image: url(/template/Admin/Images/background.png); background-repeat:repeat-x repeat-y">
    <div class="login-box" style="box-shadow: 0px 0px 30px grey">
        <div class="login-box-body">
            <img src="~/template/Admin/Images/GreenPrintHT_noneBg.png" style="margin-left:auto; margin-right:auto; display:block; width:220px; height:160px" />
            @*<br />*@
            <p class="login-box-msg" style="font-size:15px; color:darkgreen"><b>Nhập username & email để nhận lại mật khẩu</b></p>
            <form asp-action="Index" asp-controller="Login" method="post">

                <div asp-validation-summary="All" class="text-danger"></div>

                <div class="form-group has-feedback">
                    <input class="form-control py-4" asp-for="UserName" type="text" placeholder="Username..." required/>
                    <span class="glyphicon glyphicon-email form-control-feedback"></span>
                </div>
                <div class="form-group has-feedback">
                    <input class="form-control py-4" asp-for="Email" type="email" placeholder="Email..." required/>
                    <span class="glyphicon glyphicon-email form-control-feedback"></span>
                </div>
                <div class="row">
                    <div class="col-xs-8">
                        @*<div class="checkbox icheck">
                            <label>
                                <input type="checkbox"> Nhớ mật khẩu
                            </label>
                        </div>*@
                    </div><!-- /.col -->
                    <div class="col-xs-4">
                        <button type="submit" class="btn btn-success btn-block btn-flat" style="border-radius:3px; color:white">Xác nhận</button>
                    </div><!-- /.col -->
                </div>
            </form>
        </div><!-- /.login-box-body -->
    </div><!-- /.login-box -->
    <!-- jQuery 2.1.4 -->
    <script src="~/template/Admin/LTE/plugins/jQuery/jQuery-2.1.4.min.js" type="text/javascript"></script>
    <!-- Bootstrap 3.3.2 JS -->
    <script src="~/template/Admin/LTE/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
    <!-- iCheck -->
    <script src="~/template/Admin/LTE/plugins/iCheck/icheck.min.js" type="text/javascript"></script>
    <script>
        $(function () {
            $('input').iCheck({
                checkboxClass: 'icheckbox_square-blue',
                radioClass: 'iradio_square-blue',
                increaseArea: '20%' // optional
            });
        });
    </script>
</body>
</html>

PrintManagement.AdminApp/PrintManagement.AdminApp/Views/Login/Index.cshtml
@model LoginRequest
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>GreenPrint HT | Đăng nhập</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.4 -->

    <link href="~/template/Admin/LTE/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <!-- Font Awesome Icons -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <!-- Theme style -->
    <link href="~/template/Admin/LTE/dist/css/AdminLTE.min.css" rel="stylesheet" type="text/css" />
    <!-- iCheck -->
    <link href="~/template/Admin/LTE/plugins/iCheck/square/blue.css" rel="stylesheet" type="text/css" />

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body class="login-page" style="background-image: url(/template/Admin/Images/background.png); background-repeat:repeat-x repeat-y">
    <div class="login-box" style="box-shadow: 0px 0px 30px grey">
        <div class="login-box-body">
            <img src="~/template/Admin/Images/GreenPrintHT_noneBg.png" style="margin-left:auto; margin-right:auto; display:block; width:220px; height:160px" />
            @*<br />*@
            <p class="login-box-msg" style="font-size:15px; color:darkgreen"><b>Đăng nhập để bắt đầu phiên làm việc</b></p>
            <form asp-action="Index" asp-controller="Login" method="post">

                <div asp-validation-summary="All" class="text-danger"></div>

                <div class="form-group has-feedback">
                    @*<label class="small mb-1">Tài khoản</label>*@
                    <input class="form-control py-4" asp-for="UserName" type="text" placeholder="Username..." required/>
                    <span class="glyphicon glyphicon-user form-control-feedback"></span>
                </div>
                <div class="form-group has-feedback">
                    @*<label class="small mb-1">Mật khẩu</label>*@
                    <input class="form-control py-4" asp-for="Password" type="password" placeholder="Password..." required/>
                    <span class="glyphicon glyphicon-lock form-control-feedback"></span>
                </div>
                <div class="row">
                    <div class="col-xs-8">
                        <div class="checkbox icheck">
                            <label>
                                <input type="checkbox"> Nhớ mật khẩu
                            </label>
                        </div>
                    </div><!-- /.col -->
                    <div class="col-xs-4">
                        <button type="submit" class="btn btn-success btn-block btn-flat" style="border-radius:3px; color:white">Đăng nhập</button>
                    </div><!-- /.col -->
                    @*<div class="col-xs-12">
                        <p style="text-align:center">
                        @Html.ActionLink("Quên mật khẩu", "ForgetPassword", "Login")
                        </p>
                    </div>*@
                </div>
            </form>
        </div><!-- /.login-box-body -->
    </div><!-- /.login-box -->
    <!-- jQuery 2.1.4 -->
    <script src="~/template/Admin/LTE/plugins/jQuery/jQuery-2.1.4.min.js" type="text/javascript"></script>
    <!-- Bootstrap 3.3.2 JS -->
    <script src="~/template/Admin/LTE/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
    <!-- iCheck -->
    <script src="~/template/Admin/LTE/plugins/iCheck/icheck.min.js" type="text/javascript"></script>
    <script>
        $(function () {
            $('input').iCheck({
                checkboxClass: 'icheckbox_square-blue',
                radioClass: 'iradio_square-blue',
                increaseArea: '20%' // optional
            });
        });
    </script>
</body>
</html>