PrintManagement.AdminApp/PrintManagement.AdminApp/Controllers/Components/PagerViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using PrintManagement.ApiIntegration.Common;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PrintManagement.AdminApp.Controllers.Components {
    public class PagerViewComponent : ViewComponent {
        public Task<IViewComponentResult> InvokeAsync(PagedResultBase result) {
            return Task.FromResult((IViewComponentResult)View("Default", result));
        }
    }
}

PrintManagement.AdminApp/PrintManagement.AdminApp/Controllers/PrinterController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Drawing.Printing;
using System.IdentityModel.Tokens.Jwt;
using System.Linq;
using System.Management;
using System.Runtime.InteropServices;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;
using Microsoft.IdentityModel.Logging;
using Microsoft.IdentityModel.Tokens;
using PrintManagement.ApiIntegration;
using PrintManagement.ApiIntegration.Common;


namespace PrintManagement.AdminApp.Controllers {
    public class PrinterController : BaseController {
        private readonly BaseApiClient _baseApiClient;
        private readonly IPrinterApiClient _PrinterApiClient;
        private readonly ILogger _logger;

        public PrinterController(IPrinterApiClient printerApiClient,
            ILogger logger, BaseApiClient baseApiClient) {
            _logger = logger;
            _PrinterApiClient = printerApiClient;
            _baseApiClient = baseApiClient;
        }
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index(string keyword = "empty", int pageIndex = 1, int pageSize = 10) {
            if (string.IsNullOrEmpty(keyword))
                keyword = "empty";

            var data = await _PrinterApiClient.GetAllPrinter(keyword, pageSize, pageIndex);

            if (!keyword.Equals("empty"))
                ViewBag.Keyword = keyword;

            if (TempData["result"] != null)
                ViewBag.SuccessMsg = TempData["result"];

            ViewData["Token"] = HttpContext.Session.GetString(SystemConstants.AppSetting.Token);

            return View(data.ResultObj);
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Details(Guid id) {
            var result = await _PrinterApiClient.GetPrinterById(id);
            return View(result.ResultObj);
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create() {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create(PrinterDTO Printer) {
            if (!ModelState.IsValid)
                return View();

            Printer.CreatedBy = User.Claims.FirstOrDefault()?.Value;
            Printer.CreatedDate = DateTime.Now;
            Printer.ModifiedBy = User.Claims.FirstOrDefault()?.Value;
            Printer.ModifiedDate = DateTime.Now;

            //var result = await _PrinterApiClient.UpdatePrinter(Printer);
            //if (result.IsSuccessed) {
            //    TempData["result"] = "Thêm mới thiết bị thành công";
            //    return RedirectToAction("Index");
            //}

            ModelState.AddModelError("", "");
            return View(Printer);
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(Guid id) {
            var result = await _PrinterApiClient.GetPrinterById(id);
            if (result.IsSuccessed) {
                return View(result.ResultObj);
            }
            return RedirectToAction("Error", "Home");
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(PrinterDTO request) {
            if (!ModelState.IsValid)
                return View();

            request.ModifiedBy = User.Claims.FirstOrDefault()?.Value;
            request.ModifiedDate = DateTime.Now;

            var result = await _PrinterApiClient.UpdatePrinter(request.Oid, request);
            if (result.IsSuccessed) {
                TempData["result"] = "Cập nhật thiết bị thành công";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", result.Message);
            return View(request);
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(Guid id) {
            if (!ModelState.IsValid)
                return View();

            var result = await _PrinterApiClient.DeletePrinter(id);
            if (result.IsSuccessed) {
                TempData["result"] = "Xóa thiết bị thành công";
            }
            ModelState.AddModelError("", result.Message);
            return RedirectToAction("Index");
        }


        [Authorize(Roles = "Admin")]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>")]
        public async Task<IActionResult> UpdatePrinter() {
            var lstPrinter = new List<PrinterDTO>();
            var printerCollection = GetPrintersCollection();


            foreach (ManagementObject printer in printerCollection) {
                lstPrinter.Add(new PrinterDTO {
                    Oid = Guid.NewGuid(),
                    Name = Convert.ToString(printer.GetPropertyValue("Name"))?.Split('\\').LastOrDefault(),
                    DriverName = Convert.ToString(printer.GetPropertyValue("DriverName")),
                    ServerName = Convert.ToString(printer.GetPropertyValue("ServerName")),
                    PortName = Convert.ToString(printer.GetPropertyValue("PortName")),
                    Location = Convert.ToString(printer.GetPropertyValue("Location")),
                    IsNetwork = Convert.ToBoolean(printer.GetPropertyValue("Network")),
                    IsDefaultPrinter = Convert.ToBoolean(printer.GetPropertyValue("Default")),
                    Note = Convert.ToString(printer.GetPropertyValue("Description")),
                    CreatedBy = User.Claims.FirstOrDefault()?.Value,
                    CreatedDate = DateTime.Now,
                    ModifiedBy = User.Claims.FirstOrDefault()?.Value,
                    ModifiedDate = DateTime.Now,
                });
            }

            var result = await _PrinterApiClient.InsertOrUpdatePrinter(lstPrinter);
            if (result.IsSuccessed) {
                return RedirectToAction("Index");
            }
            return RedirectToAction("Error", "Home");
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Interoperability", "CA1416:Validate platform compatibility", Justification = "<Pending>")]
        public static ManagementObjectCollection GetPrintersCollection() {
            ManagementScope objMS = new ManagementScope(ManagementPath.DefaultPath);
            objMS.Connect();

            SelectQuery objQuery = new SelectQuery("SELECT * FROM Win32_Printer");
            ManagementObjectSearcher objMOS = new ManagementObjectSearcher(objMS, objQuery);
            ManagementObjectCollection printerCollection = objMOS.Get();

            return printerCollection;
        }
    }

    //class PrintSpoolerApi {
    //    [DllImport("winspool.drv", SetLastError = true, CharSet = CharSet.Auto)]
    //    public static extern bool OpenPrinter(
    //        [MarshalAs(UnmanagedType.LPTStr)]
    //        string printerName,
    //        out IntPtr printerHandle,
    //        PrinterDefaults printerDefaults);

    //    [DllImport("winspool.drv", SetLastError = true, CharSet = CharSet.Auto)]
    //    public static extern bool GetPrinter(
    //        IntPtr printerHandle,
    //        int level,
    //        IntPtr printerData,
    //        int bufferSize,
    //        ref int printerDataSize);

    //    [DllImport("winspool.drv", SetLastError = true, CharSet = CharSet.Auto)]
    //    public static extern bool GetJob(
    //        IntPtr printerHandle,
    //        int jobId,
    //        int level,
    //        IntPtr pJob,
    //        int bufferSize,
    //        ref int printerDataSize);

    //    [DllImport("winspool.drv", SetLastError = true, CharSet = CharSet.Auto)]
    //    public static extern bool ClosePrinter(
    //        IntPtr printerHandle);

    //    [StructLayout(LayoutKind.Sequential)]
    //    public struct PrinterDefaults {
    //        public IntPtr pDatatype;
    //        public IntPtr pDevMode;
    //        public int DesiredAccess;
    //    }

    //    public enum PrinterProperty {
    //        ServerName,
    //        PrinterName,
    //        ShareName,
    //        PortName,
    //        DriverName,
    //        Comment,
    //        Location,
    //        PrintProcessor,
    //        Datatype,
    //        Parameters,
    //        Attributes,
    //        Priority,
    //        DefaultPriority,
    //        StartTime,
    //        UntilTime,
    //        Status,
    //        Jobs,
    //        AveragePpm
    //    };

    //    public struct PrinterInfo2 {
    //        [MarshalAs(UnmanagedType.LPTStr)]
    //        public string ServerName;
    //        [MarshalAs(UnmanagedType.LPTStr)]
    //        public string PrinterName;
    //        [MarshalAs(UnmanagedType.LPTStr)]
    //        public string ShareName;
    //        [MarshalAs(UnmanagedType.LPTStr)]
    //        public string PortName;
    //        [MarshalAs(UnmanagedType.LPTStr)]
    //        public string DriverName;
    //        [MarshalAs(UnmanagedType.LPTStr)]
    //        public string Comment;
    //        [MarshalAs(UnmanagedType.LPTStr)]
    //        public string Location;
    //        public IntPtr DevMode;
    //        [MarshalAs(UnmanagedType.LPTStr)]
    //        public string SepFile;
    //        [MarshalAs(UnmanagedType.LPTStr)]
    //        public string PrintProcessor;
    //        [MarshalAs(UnmanagedType.LPTStr)]
    //        public string Datatype;
    //        [MarshalAs(UnmanagedType.LPTStr)]
    //        public string Parameters;
    //        public IntPtr SecurityDescriptor;

PrintManagement.AdminApp/PrintManagement.AdminApp/Views/Printer/Details.cshtml
@model PrinterDTO

@{
    ViewData["Title"] = "Thiết bị in ấn";
}

@section header
{
    Printer - Chi tiết Máy in
}

<div class="container-fluid">
    <div class="card mb-4">
        <div class="card-body">
            <div class="col-md-12">
                <dl class="row">
                    <dt class="col-sm-2">
                        Tên máy in:
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Name)
                    </dd>
                    <dt class="col-sm-2">
                        Display name:
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.DriverName)
                    </dd>
                    <dt class="col-sm-2">
                        Server name:
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.ServerName)
                        <br />
                    </dd>
                    <dt class="col-sm-2">
                        Port name:
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.PortName)
                        <br />
                    </dd>
                    <dt class="col-sm-2">
                        Máy in mặc định:
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.IsDefaultPrinter)
                        <br />
                    </dd>
                    <dt class="col-sm-2">
                        Máy in mạng:
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.IsNetwork)
                        <br />
                    </dd>
                    <dt class="col-sm-2">
                        Ví trí:
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Location)
                        <br />
                    </dd>
                    <dt class="col-sm-2">
                        Chi phí in mặc định:
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.DefaultCost)
                        <br />
                    </dd>
                    <dt class="col-sm-2">
                        Tổng jobs:
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.TotalJobs)
                        <br />
                    </dd>
                    <dt class="col-sm-2">
                        Tổng pages:
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.TotalPages)
                        <br />
                    </dd>
                    <dt class="col-sm-2">
                        Ngày sử dụng cuối:
                    </dt>
                    <dd class="col-sm-10">
                        @Html.Raw(Convert.ToDateTime(Model.LastUsageDate).ToString("dd/MM/yyyy"))
                        <br />
                    </dd>
                    <dt class="col-sm-2">
                        Ghi chú:
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Note)
                        <br />
                    </dd>
                    <dt class="col-sm-2">
                        Người tạo:
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.CreatedBy)
                        <br />
                    </dd>
                    <dt class="col-sm-2">
                        Ngày tạo:
                    </dt>
                    <dd class="col-sm-10">
                        @Html.Raw(Convert.ToDateTime(Model.CreatedDate).ToString("dd/MM/yyyy"))
                        <br />
                    </dd>
                    <dt class="col-sm-2">
                        Người cập nhật:
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.ModifiedBy)
                        <br />
                    </dd>
                    <dt class="col-sm-2">
                        Ngày cập nhật:
                    </dt>
                    <dd class="col-sm-10">
                        @Html.Raw(Convert.ToDateTime(Model.ModifiedDate).ToString("dd/MM/yyyy"))
                        <br />
                    </dd>
                </dl>
               @* <button type="button" class="btn btn-primary">
                    <a class="fa fa-edit"></a> &nbsp;
                    @Html.ActionLink("Chỉnh sửa", "Edit", new { id = Model.Oid})
                </button>*@
                <button type="button" class="btn btn-warning">
                    <a class="fa fa-th-list"></a> &nbsp;
                    @Html.ActionLink("Danh sách", "Index")
                </button>
            </div>
        </div>
    </div>
</div>

PrintManagement.AdminApp/PrintManagement.AdminApp/Views/Printer/Index.cshtml
@model PagedResult<PrinterDTO>

@{
    ViewData["Title"] = "Thiết bị in ấn";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";

    var token = ViewData["Token"] as string;

    var i = Model.PageSize * (Model.PageIndex - 1);
    string GetNumerOrder()
    {
        i++;
        return Convert.ToString(i);
    }
}
@section header
{
    Thiết bị in ấn - Danh sách máy in
}

@section Scripts{
<script>
    setTimeout(function () {
        $('#msgAlert').fadeOut('slow');
    }, 2000);
</script>
}
<div class="container-fluid">
    <div class="card mb-12">
        <div class="card-header" style="margin-bottom:12px">
            <div class="row">
                <div class="col-md-6 col-xs-12">
                    <form asp-action="Index" method="get">
                        <div class="row">
                            <div class="col-md-9">
                                <input type="text" value="@ViewBag.Keyword" name="keyword" class="form-control" placeholder="Nhập nội dung tìm kiếm..." />
                            </div>
                            <div class="cold-md-3">
                                <button type="submit" class="btn btn-primary">Tìm kiếm</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="col-md-6 col-xs-12">
                    <button type="button" class="btn btn-success btn-admin" style="margin-bottom:10px; margin-left:5px; float: right; width:110px">
                        <i class="fa fa-plus-square"></i> &nbsp;
                        @Html.ActionLink("Cập nhật", "UpdatePrinter", "Printer")
                    </button>
                </div>
            </div>
        </div>

        <div class="card-body">
            <div class="row">
                @if (ViewBag.SuccessMsg != null)
                {
                    <div id="msgAlert" class="alert alert-success" role="alert" style="position:fixed;z-index:99999;top:14%;right:35%">
                        @ViewBag.SuccessMsg
                    </div>
                }
            </div>
            <div class="table-responsive">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>
                                STT
                            </th>
                            <th>
                                Tên máy in
                            </th>
                            <th>
                                Vị trí
                            </th>
                            <th>
                                Máy in mặc định
                            </th>
                            <th>
                                Máy in mạng
                            </th>
                            <th>
                                Người cập nhật
                            </th>
                            <th>
                                Ngày cập nhật
                            </th>
                            <th>
                                Chức năng
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.Items)
                        {
                            <tr>
                                <td>
                                    @Html.Raw(GetNumerOrder())
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Name)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Location)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.IsDefaultPrinter)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.IsNetwork)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.ModifiedBy)
                                </td>
                                <td>
                                    @Html.Raw(@Convert.ToDateTime(item.ModifiedDate).ToString("dd/MM/yyyy"))
                                </td>
                                <td>
                                    @Html.ActionLink("Xem", "Details", new { id = item.Oid }) @*|*@
                                    @*@Html.ActionLink("Sửa", "Edit", new { id = item.Oid }) |
                                    @Html.ActionLink("Xóa", "Delete", new { id = item.Oid },new { onclick = "return confirm('Chắc chắn muốn xoá?');" })*@
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            @await Component.InvokeAsync("Pager", Model)
        </div>
    </div>
</div>